[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
c_boxes = "CBoxNpgGfdEjBNdtGE9WrvZWevadyzviGz7anY2fxm6M"

[registry]
url = "https://api.apr.dev"

[test.validator]
url = "https://api.devnet.solana.com/"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = ".anchor/spl_compression.so"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = ".anchor/bubblegum.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = ".anchor/noop.so"

[provider]
cluster = "Localnet"
wallet = "/Users/admin/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
create = "yarn run create"
withdraw = "yarn run withdraw"